# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='end_time_stamp',
            field=models.BigIntegerField(blank=True, help_text='End time stamp', null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='start_time_stamp',
            field=models.BigIntegerField(blank=True, help_text='Start time stamp', null=True),
        ),
    ]
