# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeches', '0002_auto_20170826_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='video_id',
            field=models.TextField(blank=True, help_text='Video id', null=True),
        ),
    ]
