# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speeches', '0003_speech_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='party',
            field=models.ForeignKey(blank=True, help_text='The party of the person making the speech', null=True, on_delete=django.db.models.deletion.CASCADE, to='speeches.Organization'),
        ),
    ]
