# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(max_length=128)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
